[[headers]]
  for = "/games/demonborn/Build/Demonborn.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/games/demonborn/Build/Demonborn.framework.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/games/demonborn/Build/Demonborn.loader.js"
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"

[[headers]]
  for = "/games/demonborn/Build/Demonborn.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"


[[headers]]
  for = "/games/behindthewall/Build/Behindthewall.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/games/behindthewall/Build/Behindthewall.framework.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/games/behindthewall/Build/Behindthewall.loader.js"
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"

[[headers]]
  for = "/games/behindthewall/Build/Behindthewall.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"